<?php if($this->enabled) : ?>
<br />
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Delivery Date')?></h3>
            <?php echo $this->getCalendar(); ?>
                <?php if($this->oktoshow): ?>
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('delivery_dates_text')->toHtml(); ?>
        <form id="dates"><input id="calendarpick" name="calendarpick" readonly="true" value="<?php echo $this->deliverydate; ?>"> <button id="Testing" class="button">Update</button><input id="customerid" name="customerid" type="hidden" value="<?php echo $this->customerid ?>"></form>
                    <script>
                        var disabledDays = <?php echo Mage::helper('deliverydates')->getDisabledDays($this->customerid) ?>;
                        $jppr('#calendarpick').datepicker({
                            minDate: '+<?php echo $this->mindate ?>D',
                            maxDate: '+<?php echo $this->maxdate ?>D',
                            beforeShowDay: function(date){
                                var day = date.getDay();
                                var disabledDates = <?php echo $this->globaldisabled ?>

                                if($jppr.inArray(day,disabledDays) != -1){
                                    return [false];
                                }
                                var string = $jppr.datepicker.formatDate('yy-mm-dd',date);
                                return [$jppr.inArray(string,disabledDates) == -1]
                            }
                        });
                    </script>
        <?php endif ?>
            </td>
        </tr>
    </table>
</div>
    <script>
        jQuery(document).ready(function ($) {
            $('#Testing').click(function (e) {
                e.preventDefault();
                $.ajax({
                    dataType: 'json',
                    type: 'post',
                    data: $('#dates').serialize(),
                    url: '<?php echo Mage::getUrl("deliverydates/ajax/updatedeliverydate/",array())?>',
                    success: function (data) {
                        if(data.response == 'success') {
                            var n = noty({
                                text: 'Delivery Date Updated',
                                type: 'success',
                                layout: 'center',
                                timeout: 1500
                            });
                        }
                        if(data.response == 'failure'){
                            var n = noty({
                                text: 'Delivery Date Update Failure: ' + data.message,
                                type: 'error',
                                layout: 'center',
                                timeout: 1500
                            });
                        }
                    }
                });
            });

//        (function ($){
//
//        }(jQuery));
//
//        function showMessage(txt, type) {
//            var html = '<ul class="messages"><li class="'+type+'-msg"><ul><li>' + txt + '</li></ul></li></ul>';
//            $jppr('div .col-main').prepend(html);
//        }
        });
    </script>
<?php endif ?>